[package]
name = "chaos-technical"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = "0.6"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
